---
- name: Create an instance
  hosts: localhost
  gather_facts: no
  tasks:
  - name: create a instance
    gcp_compute_instance:
      name: "{{ item }}"
      machine_type: n1-standard-2
      disks:
      - auto_delete: 'true'
        boot: 'true'
        initialize_params:
          disk_size_gb: 10
          source_image: projects/centos-cloud/global/images/family/centos-7
      network_interfaces:
      - network:
        access_configs:
        - name: External NAT
          nat_ip:   
          type: ONE_TO_ONE_NAT
      state: present
      tags:
        items:
        - http-server
        - https-server
      zone: us-central1-a
      project: healthy-dolphin-245407
      auth_kind: serviceaccount
      service_account_file: "~/my_account.json"
    register: abc
    with_items:
    - docker

    

  
  - name: Add host to groupname
    add_host: 
      hostname: "{{ abc.results[0].networkInterfaces[0].accessConfigs[0].natIP }}" 
      groupname: docker

- name: Manage docker host instance
  hosts: docker
  become: true
  roles:
  - docker
