---
- name: Create an instance
  hosts: localhost
  gather_facts: no
  tasks:
  - name: create a instance
    gcp_compute_instance:
      name: "{{ item }}"
      machine_type: g1-small
      disks:
      - auto_delete: 'true'
        boot: 'true'
        initialize_params:
          disk_size_gb: 10
          source_image: projects/centos-cloud/global/images/family/centos-7
      network_interfaces:
      - network:
        access_configs:
        - name: External NAT
          nat_ip:   
          type: ONE_TO_ONE_NAT
      state: present
      tags:
        items:
        - http-server
        - https-server
      zone: us-central1-a
      project: healthy-dolphin-245407
      auth_kind: serviceaccount
      service_account_file: "~/my_account.json"
    register: abc
    with_items:
    - jenkins
    
  - debug: 
      msg: "The test gcp is ready with publi_ip  {{ abc.results[0].networkInterfaces[0].accessConfigs[0].natIP }}" 
      #var: out.results[0].networkInterfaces[0].accessConfigs[0].natIP
    #register: instance
  
      # - name: Wait for SSH to come up
      #wait_for: 
      #host: "{{ out.results[0].networkInterfaces[0].accessConfigs[0].natIP }}" 
    #host: "{{ address }}" 
    #port: 22   
      #delay: 10 
      # timeout: 60

  - name: Add host to groupname
    add_host: 
      hostname: "{{ abc.results[0].networkInterfaces[0].accessConfigs[0].natIP }}" 
      groupname: test
  
  
- name: Manage new instances
  hosts: jenkins
  #onnection: ssh
  become: true
  roles:
  - jenkins
