# This task will install apache http server

- name: setup JRE environment
  yum:
    name: ['java-1.8.0','java-1.8.0-devel']
    state: present
- name: Download  Tomcat package , unzip , start service
  command: '{{ item }}'
    - curl -LO http://us.mirrors.quenda.co/apache/tomcat/tomcat-7/v7.0.96/bin/apache-tomcat-7.0.96.tar.gz
    - tar -xzf apache-tomcat-7.0.96.tar.gz 
    - apache-tomcat-7.0.96/bin/startup.sh

  #- name: Allow related and established connections
  #    iptables:
  #       chain: INPUT
  #       protocol: tcp
  #       destination_port: 7777
  #       ctstate: ESTABLISHED,RELATED
  #       jump: ACCEPT
     #become: yes
  #- name: Allow port 8080
  #shell: iptables -I INPUT -p tcp --dport 8080 -m state --state NEW,ESTABLISHED -j ACCEPT

    
