# This task will install apache http server

- name: setup JRE environment
  yum:
    name: ['java-1.8.0','java-1.8.0-devel']
    state: present
- name: Download  Tomcat package , unzip , start service
  command: '{{ item }}'
    - curl -LO http://us.mirrors.quenda.co/apache/tomcat/tomcat-7/v7.0.96/bin/apache-tomcat-7.0.96.tar.gz
    - tar -xzf apache-tomcat-7.0.96.tar.gz 
    - apache-tomcat-7.0.96/bin/startup.sh


- name: Copy tomcat config with port 7777 defined
  copy: 
    src: files/server.xml 
    dest: apache-tomcat-7.0.96/conf/server.xml

- name: Copy Tomcat users
  copy: 
    src: files/tomcat-users.xml 
    dest: apache-tomcat-7.0.96/conf/tomcat-users.xml


- name: start the tomcat service
  command: apache-tomcat-7.0.96/bin/startup.sh
      
  #- name: Allow port 8080
  #shell: iptables -I INPUT -p tcp --dport 8080 -m state --state NEW,ESTABLISHED -j ACCEPT

    
