# This task will install apache http server

- name: setup JRE environment
  yum:
    name: ['MySQL-python','unzip','java-1.8.0','java-1.8.0-devel']
    state: present
 
    #MySQL-python
- name: RPM install  MySQL 
  yum:
    name: https://github.com/github4vish/playbooks/blob/master/sonar/files/mysql-community-release-el7-5.noarch.rpm?raw=true
    state: present

- name:  Mysql server  install
  yum: 
    name: mysql-server
    state: present

- name: start the  Mysql service
  service: 
    name: mysqld
    state: started


- name: create database  Mysql server 
  become: no 
  mysql_db:
    login_user: root
    login_password: Lync123*
    name: sonar
    state: present


- name: create user and privileges on  Mysql server  
  become: no
  mysql_user: 
    login_user: root
    login_password: Lync123*
    name: sonar
    #host: localhost
    password: sonar
    priv: '*.*:ALL,GRANT'
    state: present

- name: Download  Sonar package zip , unzip
  become: no
  unarchive: 
    src: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-6.7.7.zip
    dest: /home/vish 
    remote_src: yes
    
- name: copy sonar properties
  become: no
  copy:
    src: files/sonar.properties
    dest: sonarqube-6.7.7/conf/sonar.properties

- name: Start sonar
  become: no
  command: sonarqube-6.7.7/bin/linux-x86-64/sonar.sh start




    
