
- wait_for:
    port: 8080
    delay: 10
    #command: cat /var/lib/jenkins/secrets/initialAdminPassword

- name: Get Admin Password
  become: yes
  become_method: sudo
  command: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: key

- debug:
    msg: "The jenkins password is {{ key.stdout }}"
