---
- name: Create an instance
  hosts: localhost
  gather_facts: no
  tasks:
  - name: create a instance
    gcp_compute_instance:
      name: "{{ item }}"
      machine_type: g1-small
      disks:
      - auto_delete: 'true'
        boot: 'true'
        initialize_params:
          disk_size_gb: 10
          source_image: projects/centos-cloud/global/images/family/centos-7
      network_interfaces:
      - network:
        access_configs:
        - name: External NAT
          nat_ip:   
          type: ONE_TO_ONE_NAT
      state: present
      tags:
        items:
        - http-server
        - https-server
      zone: us-central1-a
      project: healthy-dolphin-245407
      auth_kind: serviceaccount
      service_account_file: "~/my_account.json"
    register: in
    with_items:
    #- build
    - jenkins
    
      
  - name: Add host to groupname
    add_host: 
      hostname: "{{ in.results[0].networkInterfaces[0].accessConfigs[0].natIP }}"
      groupname: jenkins
  
         #  - name: Add host to groupname
         #  - aadd_host: 
         #      hostname: {{ out.results[1].networkInterfaces[0].accessConfigs[0].natIP }}
         #      groupname: jenkins
      

         #- name: Configure build
         #  hosts: build
         #  become: yes
         #  tasks:
         #  - name: install the  Build Setup
         #    yum:
         #      name: ['java-1.8.0', 'java-1.8.0-devel', 'maven']
         #      state: present  
  
 
- name: Configure jenkins
  hosts: jenkins
  become: yes
  roles:
    - jenkins
