---
#- name: Manage deploy
#  hosts: deploy
#  become: yes
#  roles:
#  - tomcat
#

- name: Manage test
  ho
  with_inventory_hostnames:
  - testi
  connection: ssh
  become: yes
  tasks:
  - name: install the  Build Setup
    yum:
      name: ['git', 'java-1.8.0', 'java-1.8.0-devel', 'maven']
      state: present  
      #with_inventory_hostnames:
      #- testi

- name: Manage jenkins
  hosts: build
  become: yes
  tasks:
  - name: install the  Build Setup
    yum:
      name: ['java-1.8.0', 'java-1.8.0-devel', 'maven']
      state: present  
